/**
 * Renders one JSON-LD graph per page.
 *
 * Google prefers a single `@graph` over several loose script tags, and it lets
 * nodes cross-reference by `@id` (Product → seller → Organization).
 */
export function JsonLd({ schemas }: { schemas: Record<string, unknown>[] }): JSX.Element {
  const graph = { '@context': 'https://schema.org', '@graph': schemas };

  return (
    <script
      type="application/ld+json"
      // Structured data is generated by us, never from user input.
      dangerouslySetInnerHTML={{ __html: JSON.stringify(graph).replace(/</g, '\\u003c') }}
    />
  );
}
